- name: Deploy Python Script to Linux VM
  hosts: webservers
  become: yes
  tasks:
    - name: Copy Python script to VM
      copy:
        src: /path/to/task2_script.py
        dest: /home/user/task2_script.py
        mode: '0755'

    - name: Ensure Python3 is installed
      apt:
        name: python3
        state: present

    - name: Run the Python script
      command: python3 /home/user/task2_script.py
